<?php

namespace Gigclub\MembershipBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembershipTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipTypeRepository extends EntityRepository
{
}
