<?php

namespace Gigclub\MembershipBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipRepository extends EntityRepository
{
	
	  public function findAll() 
	  {
	  	 return $this->findBy(array(), array('id' => 'DESC'));
	  }
}
